(function () {
  "use strict";

  window.LESSON_DATA = {
    label: "Lesson 02",
    title: "Words for dark and difficult moments",
    description: "Answer ten questions about meaning, context, synonyms, and appropriate use.",
    questions: [
      { question: "What is a corpse?", choices: [{ id: "a", text: "A dead body" }, { id: "b", text: "A loud celebration" }, { id: "c", text: "A warm shelter" }, { id: "d", text: "A written promise" }], correctAnswer: "a", explanation: "A corpse is a dead body, usually a person's body.", example: "The investigators carefully examined the corpse." },
      { question: "Which action means to conceal something?", choices: [{ id: "a", text: "Hide it" }, { id: "b", text: "Repair it" }, { id: "c", text: "Praise it" }, { id: "d", text: "Measure it" }], correctAnswer: "a", explanation: "To conceal something is to hide it from view or knowledge.", example: "The child tried to conceal the gift behind the curtain." },
      { question: "A dismal day is usually…", choices: [{ id: "a", text: "Dark, gloomy, and depressing" }, { id: "b", text: "Bright and exciting" }, { id: "c", text: "Short and noisy" }, { id: "d", text: "Warm and relaxing" }], correctAnswer: "a", explanation: "Dismal describes something that is gloomy, sad, or depressing.", example: "The dismal weather kept us inside all afternoon." },
      { question: "If the water is frigid, how does it feel?", choices: [{ id: "a", text: "Very cold" }, { id: "b", text: "Slightly sweet" }, { id: "c", text: "Very soft" }, { id: "d", text: "Quite noisy" }], correctAnswer: "a", explanation: "Frigid means extremely cold.", example: "The swimmer gasped when he entered the frigid lake." },
      { question: "What does it mean to inhabit a place?", choices: [{ id: "a", text: "To live there" }, { id: "b", text: "To build a road there" }, { id: "c", text: "To visit once" }, { id: "d", text: "To leave it quickly" }], correctAnswer: "a", explanation: "To inhabit a place means to live in it.", example: "Many small birds inhabit the forest." },
      { question: "If your hand becomes numb, it…", choices: [{ id: "a", text: "Loses much of its feeling" }, { id: "b", text: "Becomes stronger" }, { id: "c", text: "Turns bright red" }, { id: "d", text: "Moves much faster" }], correctAnswer: "a", explanation: "Numb means having little or no feeling.", example: "My fingers became numb after I held the cold bottle." },
      { question: "What is a peril?", choices: [{ id: "a", text: "A serious danger" }, { id: "b", text: "A useful tool" }, { id: "c", text: "A kind greeting" }, { id: "d", text: "A small reward" }], correctAnswer: "a", explanation: "Peril is serious danger or a dangerous situation.", example: "The guide warned us about the peril of falling rocks." },
      { question: "When you recline in a chair, you…", choices: [{ id: "a", text: "Lean back or lie down" }, { id: "b", text: "Stand on one foot" }, { id: "c", text: "Run across the room" }, { id: "d", text: "Lift a heavy box" }], correctAnswer: "a", explanation: "To recline means to lean back or rest in a partly lying position.", example: "I reclined in the chair and read a magazine." },
      { question: "A shriek is a…", choices: [{ id: "a", text: "Loud, sharp cry" }, { id: "b", text: "Quiet promise" }, { id: "c", text: "Gentle smile" }, { id: "d", text: "Slow walk" }], correctAnswer: "a", explanation: "A shriek is a sudden, high, loud cry.", example: "We heard a shriek when the mouse crossed the floor." },
      { question: "A sinister expression may seem…", choices: [{ id: "a", text: "Evil or threatening" }, { id: "b", text: "Friendly and helpful" }, { id: "c", text: "Confused but harmless" }, { id: "d", text: "Tired but cheerful" }], correctAnswer: "a", explanation: "Sinister describes something that seems evil, dangerous, or threatening.", example: "The empty house had a sinister appearance at night." },
      { question: "What does it mean to tempt someone?", choices: [{ id: "a", text: "Try to persuade that person to do something" }, { id: "b", text: "Give that person a clear warning" }, { id: "c", text: "Hide from that person" }, { id: "d", text: "Copy that person's work" }], correctAnswer: "a", explanation: "To tempt someone is to attract or persuade the person to do something.", example: "The smell of fresh bread tempted me to enter the bakery." },
      { question: "What is a wager?", choices: [{ id: "a", text: "A bet" }, { id: "b", text: "A map" }, { id: "c", text: "A secret" }, { id: "d", text: "A complaint" }], correctAnswer: "a", explanation: "A wager is an agreement to risk something on the result of a contest or event.", example: "They made a friendly wager about which team would win." },

      { question: "The museum displayed an old ____ after the investigation was complete.", choices: [{ id: "a", text: "corpse" }, { id: "b", text: "wager" }, { id: "c", text: "shriek" }, { id: "d", text: "chair" }], correctAnswer: "a", explanation: "A corpse is a dead body, so it fits this investigation context.", example: "The museum displayed an old corpse from the ancient tomb." },
      { question: "Please ____ the spare key where visitors will not see it.", choices: [{ id: "a", text: "conceal" }, { id: "b", text: "inhabit" }, { id: "c", text: "recline" }, { id: "d", text: "wager" }], correctAnswer: "a", explanation: "Conceal means hide, which is what the instruction asks you to do.", example: "Please conceal the spare key under the flowerpot." },
      { question: "The team felt hopeful despite the ____ forecast.", choices: [{ id: "a", text: "dismal" }, { id: "b", text: "frigid" }, { id: "c", text: "numb" }, { id: "d", text: "sinister" }], correctAnswer: "a", explanation: "A dismal forecast is gloomy or depressing, so feeling hopeful is a contrast.", example: "The team felt hopeful despite the dismal forecast." },
      { question: "The hikers wore extra layers during the ____ morning.", choices: [{ id: "a", text: "frigid" }, { id: "b", text: "dismal" }, { id: "c", text: "sinister" }, { id: "d", text: "numb" }], correctAnswer: "a", explanation: "Frigid means very cold, so extra layers are useful.", example: "The hikers wore extra layers during the frigid morning." },
      { question: "Several families ____ the island throughout the year.", choices: [{ id: "a", text: "inhabit" }, { id: "b", text: "tempt" }, { id: "c", text: "conceal" }, { id: "d", text: "shriek" }], correctAnswer: "a", explanation: "Inhabit means live in, which fits families living on an island.", example: "Several families inhabit the island throughout the year." },
      { question: "After sitting outside in the snow, my toes felt ____.", choices: [{ id: "a", text: "numb" }, { id: "b", text: "sinister" }, { id: "c", text: "dismal" }, { id: "d", text: "tempted" }], correctAnswer: "a", explanation: "Toes can become numb when they lose feeling because of cold.", example: "After sitting outside in the snow, my toes felt numb." },
      { question: "The broken bridge created a serious ____ for the travelers.", choices: [{ id: "a", text: "peril" }, { id: "b", text: "wager" }, { id: "c", text: "recline" }, { id: "d", text: "corpse" }], correctAnswer: "a", explanation: "Peril means danger, and a broken bridge can be dangerous.", example: "The broken bridge created a serious peril for the travelers." },
      { question: "At the end of the hike, we stopped to ____ under a tree.", choices: [{ id: "a", text: "recline" }, { id: "b", text: "conceal" }, { id: "c", text: "inhabit" }, { id: "d", text: "shriek" }], correctAnswer: "a", explanation: "Recline means lean back or lie down to rest.", example: "At the end of the hike, we stopped to recline under a tree." },
      { question: "A sudden ____ came from the dark hallway.", choices: [{ id: "a", text: "shriek" }, { id: "b", text: "wager" }, { id: "c", text: "peril" }, { id: "d", text: "corpse" }], correctAnswer: "a", explanation: "A shriek is a loud, sharp cry, which can come from a hallway.", example: "A sudden shriek came from the dark hallway." },
      { question: "The stranger's ____ smile made the children step back.", choices: [{ id: "a", text: "sinister" }, { id: "b", text: "frigid" }, { id: "c", text: "numb" }, { id: "d", text: "dismal" }], correctAnswer: "a", explanation: "Sinister means seeming evil or threatening, so the smile made them afraid.", example: "The stranger's sinister smile made the children step back." },
      { question: "The bright store window may ____ shoppers to enter.", choices: [{ id: "a", text: "tempt" }, { id: "b", text: "inhabit" }, { id: "c", text: "recline" }, { id: "d", text: "conceal" }], correctAnswer: "a", explanation: "Tempt means attract or persuade someone to do something.", example: "The bright store window may tempt shoppers to enter." },
      { question: "Mina won the ____ because her prediction was correct.", choices: [{ id: "a", text: "wager" }, { id: "b", text: "peril" }, { id: "c", text: "shriek" }, { id: "d", text: "corpse" }], correctAnswer: "a", explanation: "A wager is a bet, so Mina won after her prediction came true.", example: "Mina won the wager because her prediction was correct." },

      { question: "Which word is closest in meaning to hide?", choices: [{ id: "a", text: "Conceal" }, { id: "b", text: "Inhabit" }, { id: "c", text: "Recline" }, { id: "d", text: "Tempt" }], correctAnswer: "a", explanation: "Conceal and hide both mean to keep something from being seen.", example: "The squirrel tried to conceal the nut in the soil." },
      { question: "Which word is closest in meaning to danger?", choices: [{ id: "a", text: "Peril" }, { id: "b", text: "Wager" }, { id: "c", text: "Shriek" }, { id: "d", text: "Dismal" }], correctAnswer: "a", explanation: "Peril is another word for serious danger.", example: "The climber recognized the peril near the edge." },
      { question: "Which word is closest in meaning to extremely cold?", choices: [{ id: "a", text: "Frigid" }, { id: "b", text: "Sinister" }, { id: "c", text: "Numb" }, { id: "d", text: "Dismal" }], correctAnswer: "a", explanation: "Frigid means extremely cold.", example: "The frigid wind made the walk uncomfortable." },
      { question: "Which word is closest in meaning to gloomy?", choices: [{ id: "a", text: "Dismal" }, { id: "b", text: "Frigid" }, { id: "c", text: "Sinister" }, { id: "d", text: "Numb" }], correctAnswer: "a", explanation: "Dismal means dark, gloomy, or depressing.", example: "The empty room looked dismal without its lights." },
      { question: "Which word names a loud, high cry?", choices: [{ id: "a", text: "Shriek" }, { id: "b", text: "Wager" }, { id: "c", text: "Corpse" }, { id: "d", text: "Peril" }], correctAnswer: "a", explanation: "A shriek is a sudden loud and sharp cry.", example: "Her shriek startled the sleeping dog." },
      { question: "Which word describes a place where people or animals live?", choices: [{ id: "a", text: "Inhabit" }, { id: "b", text: "Conceal" }, { id: "c", text: "Recline" }, { id: "d", text: "Tempt" }], correctAnswer: "a", explanation: "Inhabit is the verb for living in a place.", example: "Bright fish inhabit the shallow part of the reef." },
      { question: "Which action shows that a person is reclining?", choices: [{ id: "a", text: "Leaning back on a sofa" }, { id: "b", text: "Hiding a letter" }, { id: "c", text: "Making a bet" }, { id: "d", text: "Calling loudly" }], correctAnswer: "a", explanation: "Reclining means leaning back or resting in a partly lying position.", example: "He was reclining on the sofa after dinner." },
      { question: "Which situation best shows temptation?", choices: [{ id: "a", text: "A cake smell makes you want a slice" }, { id: "b", text: "A coat keeps you warm" }, { id: "c", text: "A map shows the road" }, { id: "d", text: "A bell marks the hour" }], correctAnswer: "a", explanation: "Temptation attracts you and makes you want to do something.", example: "The smell of cookies tempted me to bake another batch." },
      { question: "Which sentence uses sinister correctly?", choices: [{ id: "a", text: "The sinister sound made us feel unsafe." }, { id: "b", text: "She drank a sinister glass of water." }, { id: "c", text: "He sinistered the book on the desk." }, { id: "d", text: "The flowers were sinister because they were colorful." }], correctAnswer: "a", explanation: "Sinister can describe something that seems frightening or evil.", example: "The sinister sound made us feel unsafe." },
      { question: "Which sentence uses wager correctly?", choices: [{ id: "a", text: "I made a wager that the train would arrive first." }, { id: "b", text: "I wagered my shoes to keep my feet warm." }, { id: "c", text: "The wager lived in the apartment." }, { id: "d", text: "She wore a wager coat in winter." }], correctAnswer: "a", explanation: "A wager is a bet about the result of an event.", example: "I made a wager that the train would arrive first." },
      { question: "Which sentence uses numb correctly?", choices: [{ id: "a", text: "The medicine made my lip numb." }, { id: "b", text: "The numb mountain was very tall." }, { id: "c", text: "We numb the apartment every summer." }, { id: "d", text: "He won a numb at the fair." }], correctAnswer: "a", explanation: "Numb describes a loss of physical feeling.", example: "The medicine made my lip numb." },
      { question: "Which sentence uses inhabit correctly?", choices: [{ id: "a", text: "Many insects inhabit the garden." }, { id: "b", text: "Please inhabit the secret in a box." }, { id: "c", text: "She inhabit a loud cry." }, { id: "d", text: "We inhabit the cold chair backward." }], correctAnswer: "a", explanation: "Inhabit means live in a place, as insects can live in a garden.", example: "Many insects inhabit the garden." }
    ]
  };
}());
