(function () {
  "use strict";

  window.LESSON_DATA = {
    label: "Lesson 01",
    title: "Words for a strong start",
    description: "Answer ten questions about meaning, context, synonyms, and appropriate use.",
    questions: [
      { question: "If a treatment alleviates pain, what does it do?", choices: [{ id: "a", text: "Makes it less severe" }, { id: "b", text: "Measures it carefully" }, { id: "c", text: "Moves it elsewhere" }, { id: "d", text: "Causes it suddenly" }], correctAnswer: "a", explanation: "To alleviate something is to make it less painful, serious, or difficult.", example: "A cool cloth helped alleviate the child's fever." },
      { question: "Which person would be an ally?", choices: [{ id: "a", text: "Someone who supports your goal" }, { id: "b", text: "Someone who ignores every plan" }, { id: "c", text: "Someone who sells a ticket" }, { id: "d", text: "Someone who arrives late" }], correctAnswer: "a", explanation: "An ally is a person or group that joins with and supports another.", example: "The neighboring club became an ally in the cleanup project." },
      { question: "The complicated map began to bewilder the hikers. What happened?", choices: [{ id: "a", text: "It confused them" }, { id: "b", text: "It encouraged them" }, { id: "c", text: "It warned them" }, { id: "d", text: "It amused them" }], correctAnswer: "a", explanation: "To bewilder someone is to confuse that person completely.", example: "The unfamiliar instructions bewildered me." },
      { question: "Which description best fits a bona fide expert?", choices: [{ id: "a", text: "A genuine, qualified expert" }, { id: "b", text: "A temporary visitor" }, { id: "c", text: "A very nervous beginner" }, { id: "d", text: "A person who dislikes experts" }], correctAnswer: "a", explanation: "Bona fide means real, genuine, or sincere.", example: "The museum hired a bona fide scientist to check the fossils." },
      { question: "A brusque reply is usually…", choices: [{ id: "a", text: "Short and not very polite" }, { id: "b", text: "Long and poetic" }, { id: "c", text: "Warm and playful" }, { id: "d", text: "Careful and secret" }], correctAnswer: "a", explanation: "Brusque describes speech or behavior that is very brief and may seem rude.", example: "His brusque answer ended the conversation." },
      { question: "In the sentence “One caveat is the cost,” what does caveat mean?", choices: [{ id: "a", text: "A warning or condition" }, { id: "b", text: "A celebration" }, { id: "c", text: "A reward" }, { id: "d", text: "A written apology" }], correctAnswer: "a", explanation: "A caveat is a warning that tells you about a possible problem or limit.", example: "The plan sounds good, with one caveat: it may take two months." },
      { question: "Why might a town commemorate an important event?", choices: [{ id: "a", text: "To honor and remember it" }, { id: "b", text: "To hide it from everyone" }, { id: "c", text: "To change its date" }, { id: "d", text: "To sell it to another town" }], correctAnswer: "a", explanation: "To commemorate an event is to honor it and keep its memory alive.", example: "The statue was built to commemorate the town's founders." },
      { question: "A consensus has been reached when…", choices: [{ id: "a", text: "Most or all people agree" }, { id: "b", text: "Nobody has heard the idea" }, { id: "c", text: "One person refuses to speak" }, { id: "d", text: "A meeting starts late" }], correctAnswer: "a", explanation: "Consensus is general agreement among the members of a group.", example: "After a short discussion, the team reached a consensus." },
      { question: "The culmination of months of practice was the final concert. What is the culmination?", choices: [{ id: "a", text: "The highest or final point" }, { id: "b", text: "The first small mistake" }, { id: "c", text: "A private rehearsal" }, { id: "d", text: "A list of unused tools" }], correctAnswer: "a", explanation: "The culmination is the final or most important point of a process.", example: "Winning the award was the culmination of her hard work." },
      { question: "If you decipher a coded message, you…", choices: [{ id: "a", text: "Work out its meaning" }, { id: "b", text: "Erase it completely" }, { id: "c", text: "Read it aloud to a crowd" }, { id: "d", text: "Translate it into music" }], correctAnswer: "a", explanation: "To decipher something is to discover the meaning of writing that is difficult to understand.", example: "The detective tried to decipher the note." },
      { question: "Which student is diligent?", choices: [{ id: "a", text: "One who works carefully and steadily" }, { id: "b", text: "One who quits after one minute" }, { id: "c", text: "One who loses every book" }, { id: "d", text: "One who never checks the work" }], correctAnswer: "a", explanation: "A diligent person works hard and takes care with the work.", example: "Maya is diligent about practicing her spelling." },
      { question: "The runner tried to elude the reporters. What did the runner try to do?", choices: [{ id: "a", text: "Avoid being caught or followed" }, { id: "b", text: "Answer every question" }, { id: "c", text: "Invite them to dinner" }, { id: "d", text: "Give them directions" }], correctAnswer: "a", explanation: "To elude someone is to escape from or avoid that person.", example: "The clever fox eluded the dogs in the forest." },
      { question: "What happens when a book engrosses you?", choices: [{ id: "a", text: "It holds all your attention" }, { id: "b", text: "It makes you fall asleep at once" }, { id: "c", text: "It becomes impossible to open" }, { id: "d", text: "It teaches you to draw" }], correctAnswer: "a", explanation: "To engross someone is to interest that person so much that all attention is held.", example: "The mystery novel engrossed me on the long train ride." },
      { question: "Which project is feasible?", choices: [{ id: "a", text: "One that can realistically be done" }, { id: "b", text: "One that breaks every rule" }, { id: "c", text: "One that has no clear purpose" }, { id: "d", text: "One that already failed" }], correctAnswer: "a", explanation: "Something feasible is possible and practical to do.", example: "A small garden is a feasible project for this space." },
      { question: "A fervent supporter feels…", choices: [{ id: "a", text: "Strong and passionate support" }, { id: "b", text: "Complete uncertainty" }, { id: "c", text: "Mild boredom" }, { id: "d", text: "A need to leave" }], correctAnswer: "a", explanation: "Fervent means showing strong feeling, enthusiasm, or devotion.", example: "She is a fervent supporter of public libraries." },
      { question: "If a storm is imminent, it is…", choices: [{ id: "a", text: "About to happen soon" }, { id: "b", text: "Already forgotten" }, { id: "c", text: "Very far away" }, { id: "d", text: "Impossible to predict" }], correctAnswer: "a", explanation: "Imminent describes something that is about to happen.", example: "Dark clouds showed that a storm was imminent." },
      { question: "A lucid explanation is easy to…", choices: [{ id: "a", text: "Understand" }, { id: "b", text: "Hide" }, { id: "c", text: "Forget" }, { id: "d", text: "Paint" }], correctAnswer: "a", explanation: "Lucid means clear and easy to understand.", example: "The guide gave a lucid explanation of the rules." },
      { question: "What does the majority of a group represent?", choices: [{ id: "a", text: "More than half of the group" }, { id: "b", text: "Exactly one person" }, { id: "c", text: "The newest member only" }, { id: "d", text: "Less than one quarter" }], correctAnswer: "a", explanation: "The majority is the larger number or part of a group, usually more than half.", example: "The majority of voters chose the new park design." },
      { question: "Which action is meticulous?", choices: [{ id: "a", text: "Checking every small detail" }, { id: "b", text: "Rushing without looking" }, { id: "c", text: "Guessing a random answer" }, { id: "d", text: "Leaving a task unfinished" }], correctAnswer: "a", explanation: "A meticulous person is extremely careful about details.", example: "He kept meticulous notes during the experiment." },
      { question: "A novice is someone who is…", choices: [{ id: "a", text: "New to an activity" }, { id: "b", text: "The best possible teacher" }, { id: "c", text: "Against all new ideas" }, { id: "d", text: "Unable to make a choice" }], correctAnswer: "a", explanation: "A novice is a beginner who has little experience.", example: "As a novice gardener, I started with three easy plants." },
      { question: "An obsolete machine is…", choices: [{ id: "a", text: "No longer useful or current" }, { id: "b", text: "Brand new and popular" }, { id: "c", text: "Too small to see" }, { id: "d", text: "Designed for travel" }], correctAnswer: "a", explanation: "Obsolete means no longer used because something newer works better.", example: "The old printer became obsolete after the office changed systems." },
      { question: "Which idea sounds plausible?", choices: [{ id: "a", text: "It seems reasonable and possible" }, { id: "b", text: "It clearly breaks the laws of nature" }, { id: "c", text: "Nobody can describe it" }, { id: "d", text: "It has already been disproved" }], correctAnswer: "a", explanation: "Plausible means seeming reasonable or likely to be true.", example: "Her plausible explanation matched the evidence." },
      { question: "If you relinquish your seat, you…", choices: [{ id: "a", text: "Give it up or let someone else have it" }, { id: "b", text: "Paint it a new color" }, { id: "c", text: "Reserve two more seats" }, { id: "d", text: "Hide it from the room" }], correctAnswer: "a", explanation: "To relinquish something is to give it up or stop holding it.", example: "He relinquished his seat to an older passenger." },
      { question: "A tenacious person keeps trying because they are…", choices: [{ id: "a", text: "Determined and persistent" }, { id: "b", text: "Easily distracted" }, { id: "c", text: "Unwilling to learn" }, { id: "d", text: "Always in a hurry" }], correctAnswer: "a", explanation: "Tenacious describes someone who does not give up easily.", example: "The tenacious player practiced until she mastered the skill." }
    ]
  };
}());
